repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/google/yamlfmt
    rev: v0.13.0
    hooks:
      - id: yamlfmt
        args: ["-formatter", "type=basic,indent=2,include_document_start=false"]

  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.26.0
    hooks:
      - id: sqlfmt
        files: ^dbt/.*\.sql$
