FROM apache/airflow:2.9.2-python3.11

USER root
COPY requirements/airflow.txt /opt/airflow/requirements.txt
RUN chown airflow /opt/airflow/requirements.txt

USER airflow
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r /opt/airflow/requirements.txt
